services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    entrypoint:
      - bin/web-entrypoint.sh

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:${POSTGRES_PORT}"
