#!/bin/bash

# shellcheck disable=SC2086

set -o errexit
set -o pipefail
set -o nounset

DC="${DC:-exec}"
OLD_COMPOSE_FILE="${COMPOSE_FILE:-}"
export COMPOSE_FILE="${COMPOSE_FILE:-compose.yaml}"
COMPOSE_ARGS=""


# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _build {
  # Build the app and all its dependencies
  docker compose $COMPOSE_ARGS build --no-cache
}

function _dc {
  docker compose $COMPOSE_ARGS "${DC}" "${@}"
}

function _build_run_down {
  _build
  docker compose $COMPOSE_ARGS run "${@}"
  docker compose $COMPOSE_ARGS down
}

# -----------------------------------------------------------------------------

function build {
  # Build the app and all its dependencies
  _build "${@}"
}

function up {
  # Start the app and all its dependencies
  docker compose $COMPOSE_ARGS up -d "${@}"
}

function down {
  # Stop the app and all its dependencies
  docker compose $COMPOSE_ARGS down "${@}"
}

function cmd {
  # Run any command you want in the app container
  _dc app "${@}"
}

function pip-install {
  # Install python requirements from
  _build_run_down app /app/bin/pip3-install.sh
}

function format {
  # Format Python code
  cmd black . "${@}"
}

function test {
  # Run pytest
  cmd python -m pytest "${@}"
}

function shell {
  # Start a shell session in the app container
  cmd bash "${@}"
}

function manage {
  # Run Django management commands
  cmd python manage.py "${@}"
}

function logs {
  docker compose logs
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"

export COMPOSE_FILE=$OLD_COMPOSE_FILE
